name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
      - 'architecture_diagrams/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'architecture_diagrams/**'

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --target test --tag test-image .
    - run: docker run --env-file .env.test test-image
  push-image:
    name: Build and push image
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/exercise-9'
    runs-on: ubuntu-latest
    steps:
    - run: echo Publishing!
